name: user_repository
description: "the repo that handles users"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true