// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4H8KBd5QMIlvT-2NzaVQX_yQTSPI2gy0',
    appId: '1:247352582669:web:144eccd315a865b391ab44',
    messagingSenderId: '247352582669',
    projectId: 'login-with-firebase-55b64',
    authDomain: 'login-with-firebase-55b64.firebaseapp.com',
    storageBucket: 'login-with-firebase-55b64.appspot.com',
    measurementId: 'G-HHJSGNHJPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdkOtULt56iVHyAsFBSJVxjO46zGcCj0',
    appId: '1:247352582669:android:9e1c144b136a303691ab44',
    messagingSenderId: '247352582669',
    projectId: 'login-with-firebase-55b64',
    storageBucket: 'login-with-firebase-55b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu66YCMoa444kOKJOpkPIXTxfeJ4dENVk',
    appId: '1:247352582669:ios:dffbc7dfc1f890fc91ab44',
    messagingSenderId: '247352582669',
    projectId: 'login-with-firebase-55b64',
    storageBucket: 'login-with-firebase-55b64.appspot.com',
    iosBundleId: 'com.example.loginWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu66YCMoa444kOKJOpkPIXTxfeJ4dENVk',
    appId: '1:247352582669:ios:dffbc7dfc1f890fc91ab44',
    messagingSenderId: '247352582669',
    projectId: 'login-with-firebase-55b64',
    storageBucket: 'login-with-firebase-55b64.appspot.com',
    iosBundleId: 'com.example.loginWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4H8KBd5QMIlvT-2NzaVQX_yQTSPI2gy0',
    appId: '1:247352582669:web:dcc29815e088384b91ab44',
    messagingSenderId: '247352582669',
    projectId: 'login-with-firebase-55b64',
    authDomain: 'login-with-firebase-55b64.firebaseapp.com',
    storageBucket: 'login-with-firebase-55b64.appspot.com',
    measurementId: 'G-2G3S6386PV',
  );
}
